server:
  port: 8080
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/jierui?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: root
  #redis相关配置
  redis:
    host: 192.168.100.101
    port: 6379
#    password: 123456
    database: 0
    jedis:
      #redis连接池配置
      pool:
        max-active: 8 #最大连接数
        max-wait: 1ms #连接池最大阻塞等待时间
        max-idle: 4 #连接池中的最大空闲连接
        min-idle: 0 #连接池中的最小空闲连接
mybatis:
  configuration:
    map-underscore-to-camel-case: true
jierui:
  path: D:\leiyuan\JavaWebCode\SpringBoot\jierui\jierui_end\src\main\resources\static\img\
